config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  get 'static_pages/home'
  root 'static_pages#home'
  get  '/courses', to: 'courses#index'
  get  '/contact', to: 'static_pages#contact'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'students#new'
  post '/signup',  to: 'students#create'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'
  get  '/top_rated_courses', to: 'courses#top_rated_courses'
  get 'courses/:id/next', to: 'courses#next'



  resources :students

  resources :courses do
    resources :categories, :ratings, :only => [:new, :index, :create]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p id="text-center">The Analytics Rating App is a web application built with Ruby On Rails, Boostrap and a SQLite database.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact Us") %>
<h1>Contact Us</h1>
<p>Contact the Ruby on Rails Tutorial about the sample app at the <a href="https://www.railstutorial.org/contact">contact page</a>.</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="center jumbotron">
  <h1>Welcome to the Analytics Rating App</h1>

  <h2>A Rails and JavaScript application where you can rate analytics related courses.</h2>
  <div class="flex">
  <h3><%= link_to "Login", login_path, class: "btn btn-lg btn-primary" %></h3>
  &nbsp;&nbsp;
  <h3><%= link_to "Login with Facebook", '/auth/facebook', class: "btn btn-lg btn-primary" %></h3>
  &nbsp;&nbsp;
  <h3><%= link_to "Sign Up", signup_path, class: "btn btn-lg btn-primary" %></h3>
  </div>
</div>