config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  get 'static_pages/home'
  root 'static_pages#home'
  get  '/courses', to: 'courses#index'
  get  '/contact', to: 'static_pages#contact'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'students#new'
  post '/signup',  to: 'students#create'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'
  get  '/top_rated_courses', to: 'courses#top_rated_courses'
  get 'courses/:id/next', to: 'courses#next'



  resources :students

  resources :courses do
    resources :categories, :ratings, :only => [:new, :index, :create]
  end
end

app/models/rating.rb
class Rating < ApplicationRecord

  belongs_to :student
  belongs_to :course

  validates :rating,
            #uniqueness: true,
            numericality: { less_than_or_equal_to: 5,
            greater_than: 0,
            only_integer: true }


    def self.average_rating
      if average(:rating) == nil
        0
      else
        average(:rating).round(2)
      end
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def index
    @course = Course.find_by_id(params[:course_id])
    if @course
      @ratings = @course.ratings
    else
      redirect_to courses_path
    end
  end

  def new
    @course = Course.find_by_id(params[:course_id])
    #@rating = Rating.new(course: @course)   this line is the same as the one below
    @rating = @course.ratings.build
  end

  def create
    #@course = Course.find_by_id(params[:course_id])
    @rating = current_student.ratings.build(rating_params)
    #@rating.course = @course
    if @rating.save
      redirect_to course_path(@rating.course)
    else
      render :new
    end
  end

  def top_rated_classes
  end
  private

  def rating_params
    params.require(:rating).permit(:rating, :course_id )
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for @rating do |form| %>

  <% if @rating.errors.any? %>
     <div id="error_explanation">
       <h2>
         <%= pluralize(@rating.errors.count, "error") %> prohibited
         this rating from being saved:
       </h2>
       <ul>
         <% @rating.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>

    <%= form.hidden_field :course_id %>
  <p>
    <%= form.label :rating, "Add a number between 1-5" %><br>
    <%= form.number_field :rating, min: 0, max: 5 %>
  </p>
  <p>
    <%= form.submit "Submit Rating"%>
  </p>
<% end %>

app/views/ratings/index.html.erb
<% provide(:title, 'All ratings') %>
<h1>Ratings for: <%= @course.name%> </h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">

  <ul id="check-mark">
    <% @ratings.each do |f| %>
      <li>Rating by <%= f.student.first_name %>: <%= f.rating %></li>
    <% end %>
  </ul>
 </div>
</div>
<p id="text-center"><%= link_to 'Back', ratings_path %></p>

app/views/ratings/new.html.erb
<% provide(:title, 'Course Rating') %>
<h1>What's Your Rating for <%= @rating.course.name%>?</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>